### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by AwuorMarvin**

### CODE REVIEW

**Comment by JayKay24** [comment]
Nice and intuitive user interface. Nice wireframes. Good atomic commits.

**Review by mkiterian — CHANGES_REQUESTED** [review]
Thanks so much for this feedback. Let me try and incorporate the changes. Thanks again.
Wireframes looking good
Check on:
Can't see a logout feature
Navbar indicates an activities panel yet there is no view for it
* Commit messages should be in imperative form (Like giving a command)

**Comment by machariamarigi** [comment]
Good work on the design and wireframes. Avoid writing commits in past tense

**Comment by Chris-Maina** [comment]
Good work. Try not to use past tense on the commits. Something like Add... is preferred

**Comment by Chris-Maina** [comment]
Good work.  Try avoid past tense in your commits. Try something like Add..

**Pull request merged**
